import sqlite3
from pathlib import Path
from datetime import datetime

DB_PATH = Path(__file__).resolve().parent / "ai_scholarship_finder.db"
SCHEMA_PATH = Path(__file__).resolve().parent / "schema.sql"

SCHOLARSHIPS = [
    {
        "name": "Global STEM Excellence Scholarship",
        "provider": "STEM Future Foundation",
        "description": "Supports high-achieving STEM students worldwide.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "STEM",
        "min_gpa": 3.5,
        "max_income": 60000,
        "min_age": 17,
        "max_age": 30,
        "award_amount": 8000,
        "deadline": "2025-03-15",
    },
    {
        "name": "Women in Tech Scholars",
        "provider": "Tech Equity Alliance",
        "description": "Empowering women pursuing computing and engineering.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Computer Science",
        "min_gpa": 3.2,
        "max_income": 70000,
        "min_age": 18,
        "max_age": 32,
        "award_amount": 10000,
        "deadline": "2025-05-01",
    },
    {
        "name": "AI Research Fellowship",
        "provider": "AI for Good Lab",
        "description": "Funding for graduate research in AI and data science.",
        "country": "Any",
        "education_level": "Master",
        "field": "Artificial Intelligence",
        "min_gpa": 3.6,
        "max_income": 90000,
        "min_age": 21,
        "max_age": 40,
        "award_amount": 15000,
        "deadline": "2025-02-20",
    },
    {
        "name": "Community Leadership Scholarship",
        "provider": "Bright Communities",
        "description": "Recognizes students committed to community service.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Social Sciences",
        "min_gpa": 3.0,
        "max_income": 50000,
        "min_age": 17,
        "max_age": 29,
        "award_amount": 5000,
        "deadline": "2025-04-10",
    },
    {
        "name": "Green Energy Innovators Grant",
        "provider": "EcoPower Initiative",
        "description": "Supports renewable energy and sustainability students.",
        "country": "Any",
        "education_level": "Master",
        "field": "Environmental Engineering",
        "min_gpa": 3.4,
        "max_income": 80000,
        "min_age": 20,
        "max_age": 35,
        "award_amount": 12000,
        "deadline": "2025-06-05",
    },
    {
        "name": "Future Nurses Scholarship",
        "provider": "HealthFirst Foundation",
        "description": "For students entering nursing programs.",
        "country": "USA",
        "education_level": "Bachelor",
        "field": "Nursing",
        "min_gpa": 3.1,
        "max_income": 65000,
        "min_age": 18,
        "max_age": 35,
        "award_amount": 7000,
        "deadline": "2025-03-30",
    },
    {
        "name": "Global Business Leaders",
        "provider": "World Commerce Fund",
        "description": "Supports business students with leadership potential.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Business",
        "min_gpa": 3.3,
        "max_income": 75000,
        "min_age": 18,
        "max_age": 30,
        "award_amount": 9000,
        "deadline": "2025-04-22",
    },
    {
        "name": "Rural Education Access Award",
        "provider": "Rural Scholars Network",
        "description": "Assists students from rural communities.",
        "country": "Any",
        "education_level": "Associate",
        "field": "Education",
        "min_gpa": 2.8,
        "max_income": 45000,
        "min_age": 17,
        "max_age": 28,
        "award_amount": 4000,
        "deadline": "2025-07-01",
    },
    {
        "name": "Cybersecurity Defense Scholarship",
        "provider": "SecureNet",
        "description": "Supports cybersecurity certifications and degrees.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Cybersecurity",
        "min_gpa": 3.2,
        "max_income": 85000,
        "min_age": 18,
        "max_age": 34,
        "award_amount": 11000,
        "deadline": "2025-05-18",
    },
    {
        "name": "Creative Arts Fellowship",
        "provider": "Arts United",
        "description": "Encourages emerging artists and designers.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Arts",
        "min_gpa": 3.0,
        "max_income": 55000,
        "min_age": 17,
        "max_age": 29,
        "award_amount": 6000,
        "deadline": "2025-04-05",
    },
    {
        "name": "PhD Quantum Computing Grant",
        "provider": "Quantum Leap Institute",
        "description": "Research funding for quantum computing PhD candidates.",
        "country": "Any",
        "education_level": "PhD",
        "field": "Quantum Computing",
        "min_gpa": 3.7,
        "max_income": 100000,
        "min_age": 23,
        "max_age": 45,
        "award_amount": 20000,
        "deadline": "2025-08-20",
    },
    {
        "name": "Data Science Innovators",
        "provider": "Insight Analytics",
        "description": "Supports students specializing in data science.",
        "country": "Any",
        "education_level": "Master",
        "field": "Data Science",
        "min_gpa": 3.4,
        "max_income": 90000,
        "min_age": 20,
        "max_age": 38,
        "award_amount": 13000,
        "deadline": "2025-02-28",
    },
    {
        "name": "Public Policy Scholars",
        "provider": "Policy Futures",
        "description": "Scholarships for students in public policy programs.",
        "country": "Any",
        "education_level": "Master",
        "field": "Public Policy",
        "min_gpa": 3.2,
        "max_income": 70000,
        "min_age": 21,
        "max_age": 40,
        "award_amount": 10000,
        "deadline": "2025-06-15",
    },
    {
        "name": "First-Gen College Grant",
        "provider": "NextGen Scholars",
        "description": "Supports first-generation college students.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Any",
        "min_gpa": 2.9,
        "max_income": 48000,
        "min_age": 17,
        "max_age": 30,
        "award_amount": 5500,
        "deadline": "2025-09-01",
    },
    {
        "name": "Healthcare Administration Award",
        "provider": "Health Policy Council",
        "description": "For students pursuing healthcare administration.",
        "country": "Any",
        "education_level": "Master",
        "field": "Healthcare Administration",
        "min_gpa": 3.3,
        "max_income": 85000,
        "min_age": 21,
        "max_age": 40,
        "award_amount": 9500,
        "deadline": "2025-03-12",
    },
    {
        "name": "Global Agriculture Scholarship",
        "provider": "AgriWorld",
        "description": "Supporting agriculture and food science students.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Agriculture",
        "min_gpa": 3.0,
        "max_income": 60000,
        "min_age": 18,
        "max_age": 32,
        "award_amount": 7000,
        "deadline": "2025-07-20",
    },
    {
        "name": "Urban Planning Fellowship",
        "provider": "City Futures",
        "description": "Supports urban planning and design programs.",
        "country": "Any",
        "education_level": "Master",
        "field": "Urban Planning",
        "min_gpa": 3.2,
        "max_income": 80000,
        "min_age": 22,
        "max_age": 40,
        "award_amount": 11000,
        "deadline": "2025-05-25",
    },
    {
        "name": "International Student Success",
        "provider": "Global Access",
        "description": "Scholarship for international students in the UK.",
        "country": "UK",
        "education_level": "Bachelor",
        "field": "Any",
        "min_gpa": 3.1,
        "max_income": 65000,
        "min_age": 18,
        "max_age": 33,
        "award_amount": 8000,
        "deadline": "2025-04-18",
    },
    {
        "name": "FinTech Rising Stars",
        "provider": "Digital Finance Group",
        "description": "Support for fintech and finance technology students.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "FinTech",
        "min_gpa": 3.3,
        "max_income": 75000,
        "min_age": 18,
        "max_age": 30,
        "award_amount": 8500,
        "deadline": "2025-06-30",
    },
    {
        "name": "Biomedical Discovery Grant",
        "provider": "LifeScience Trust",
        "description": "Funding for biomedical science students.",
        "country": "Any",
        "education_level": "Master",
        "field": "Biomedical Science",
        "min_gpa": 3.5,
        "max_income": 95000,
        "min_age": 20,
        "max_age": 38,
        "award_amount": 14000,
        "deadline": "2025-03-28",
    },
    {
        "name": "Engineering for Humanity",
        "provider": "Engineers Without Borders",
        "description": "Scholarship for humanitarian engineering projects.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Engineering",
        "min_gpa": 3.2,
        "max_income": 70000,
        "min_age": 18,
        "max_age": 30,
        "award_amount": 9000,
        "deadline": "2025-05-10",
    },
    {
        "name": "Global MBA Advantage",
        "provider": "Leadership Bridge",
        "description": "MBA scholarship for emerging leaders.",
        "country": "Any",
        "education_level": "Master",
        "field": "MBA",
        "min_gpa": 3.4,
        "max_income": 100000,
        "min_age": 24,
        "max_age": 40,
        "award_amount": 16000,
        "deadline": "2025-09-15",
    },
    {
        "name": "Clean Water Engineering Prize",
        "provider": "WaterWorks",
        "description": "Supports students focused on water systems.",
        "country": "Any",
        "education_level": "Bachelor",
        "field": "Civil Engineering",
        "min_gpa": 3.1,
        "max_income": 60000,
        "min_age": 18,
        "max_age": 32,
        "award_amount": 7500,
        "deadline": "2025-08-10",
    },
]


def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(DB_PATH) as conn:
        conn.executescript(SCHEMA_PATH.read_text())
        existing = conn.execute("SELECT COUNT(*) FROM scholarships").fetchone()[0]
        if existing:
            return
        conn.executemany(
            """
            INSERT INTO scholarships (
                name, provider, description, country, education_level, field,
                min_gpa, max_income, min_age, max_age, award_amount, deadline
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    s["name"],
                    s["provider"],
                    s["description"],
                    s["country"],
                    s["education_level"],
                    s["field"],
                    s["min_gpa"],
                    s["max_income"],
                    s["min_age"],
                    s["max_age"],
                    s["award_amount"],
                    s["deadline"],
                )
                for s in SCHOLARSHIPS
            ],
        )
        conn.commit()


if __name__ == "__main__":
    init_db()
    print(f"Database initialized with {len(SCHOLARSHIPS)} scholarships at {DB_PATH}")
